#!/usr/bin/env python3

import os
import sys


class HWDef:

    def __init__(self, filename):
        self.filename = filename
        self.data = {}

    def parse(self):

        with open(self.filename, "r") as f:

            for line in f:

                line = line.strip()

                if not line or line.startswith("#"):
                    continue

                words = line.split()

                key = words[0]
                value = " ".join(words[1:])

                self.data[key] = value

    def print(self):

        print("--------------------------------")
        print("MiniPilot Board Definition")
        print("--------------------------------")

        for k, v in self.data.items():
            print(f"{k:20} : {v}")

        print("--------------------------------")

    def generate_board_header(self):

        os.makedirs("generated", exist_ok=True)

        with open("generated/board.h", "w") as f:

            f.write("/*\n")
            f.write(" * Auto-generated by MiniPilot\n")
            f.write(" * Do NOT edit manually.\n")
            f.write(" */\n\n")

            f.write("#ifndef BOARD_H\n")
            f.write("#define BOARD_H\n\n")

            for key, value in self.data.items():

                if key == "END":
                    continue

                if value.isdigit():
                    f.write(f"#define {key} {value}\n")
                else:
                    f.write(f'#define {key} "{value}"\n')

            f.write("\n#endif\n")


def main():

    if len(sys.argv) != 2:

        print("Usage:")
        print("python3 hwdef.py <hwdef.dat>")
        return

    board = HWDef(sys.argv[1])

    board.parse()

    board.print()

    board.generate_board_header()

    print("Generated: generated/board.h")


if __name__ == "__main__":
    main()
